name: Build SnowOS ISO

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SnowOS
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            gcc \
            g++ \
            nasm \
            grub-pc-bin \
            grub-common \
            xorriso \
            mtools \
            qemu-system-x86

      - name: Make build script executable
        run: chmod +x build.sh

      - name: Build SnowOS
        run: ./build.sh

      - name: Find generated ISO
        run: |
          echo "Searching for ISO..."
          find . -type f -name "*.iso" -print

      - name: Upload SnowOS ISO
        uses: actions/upload-artifact@v4
        with:
          name: SnowOS-ISO
          path: "**/*.iso"
          if-no-files-found: error
